name: Sample Workflow

# This workflow is triggered whenever a new PR is created on the main branch
on:
  workflow_dispatch:

jobs:

  test:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'Checkout repository'
      - name: Set up cache for maven
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: 'Run Tests'
        run: mvn clean install
      - name: 'See workspace'
        run: |
          cd ${{ github.workspace }}
          ls -al
      - name: 'Java version'
        run: java -version
        

