name: Sample Workflow

on:
  workflow_dispatch:

jobs:

  test:
    name: 'Checkout the repo'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'Checkout repository'
      - name: 'Run Tests'
        run: mvn clean install
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workspace }} # or path/to/artifact/
  sonar:
    name: 'SonarQube Scan'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        name: 'Checkout repository'
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - name: See workspace
        run: |
          echo '${{ github.workspace }}'
          cd ${{ github.workspace }}
          ls -la

        

